
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class ABP extends javax.swing.JFrame {
    
    public int id;
    public String clave;
    public String clave2;
    public String nombre;
    public String apellido;
    public String fnaci;
    public int semestre;
    public String email;
    public String genero;
    public long telefono;
    public String programa;
    public String universidad;

    /**
     * Creates new form ABP
     */
    public ABP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaClave = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        txtReClave = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        etiClave = new javax.swing.JLabel();
        diaRegistro = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtSemestre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPrograma = new javax.swing.JTextField();
        txtUniversidad = new javax.swing.JTextField();
        btnFinRegistro = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        diaDatos = new javax.swing.JDialog();
        cboDatos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        etiResultado = new javax.swing.JLabel();
        etiImagen = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("CREAR CLAVE");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("La clave tiene que tener al menos una Mayuscula");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Un numero y un caracter diferente al numero o letra");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Y minimo 8 caracteres");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel6.setText("CLAVE:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setText("REPITA LA CLVE:");

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaClaveLayout = new javax.swing.GroupLayout(diaClave.getContentPane());
        diaClave.getContentPane().setLayout(diaClaveLayout);
        diaClaveLayout.setHorizontalGroup(
            diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaClaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaClaveLayout.createSequentialGroup()
                        .addGap(0, 57, Short.MAX_VALUE)
                        .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaClaveLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(164, 164, 164))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaClaveLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(80, 80, 80)))))
                    .addGroup(diaClaveLayout.createSequentialGroup()
                        .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(56, 56, 56)
                        .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReClave)
                            .addComponent(txtClave))
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaClaveLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(etiClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diaClaveLayout.setVerticalGroup(
            diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaClaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaClaveLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)
                        .addGap(23, 23, 23))
                    .addGroup(diaClaveLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(diaClaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtReClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(etiClave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        diaRegistro.setTitle("REGISTRO");

        jLabel8.setText("ID:");

        jLabel9.setText("NOMBRE:");

        jLabel10.setText("APELLIDOS:");

        jLabel11.setText("F/NACIMIENTO:");

        jLabel12.setText("SEMESTRE:");

        jLabel13.setText("EMAIL:");

        jLabel14.setText("GENERO:");

        jLabel15.setText("TELEFONO:");

        jLabel16.setText("PROGRAMA:");

        jLabel17.setText("UNIVERSIDAD:");

        btnFinRegistro.setText("FIN REGISTRO");
        btnFinRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinRegistroActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaRegistroLayout = new javax.swing.GroupLayout(diaRegistro.getContentPane());
        diaRegistro.getContentPane().setLayout(diaRegistroLayout);
        diaRegistroLayout.setHorizontalGroup(
            diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(diaRegistroLayout.createSequentialGroup()
                        .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(34, 34, 34)
                        .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtNombre)
                            .addComponent(txtApellidos)
                            .addComponent(txtNacimiento)
                            .addComponent(txtSemestre)
                            .addComponent(txtEmail)
                            .addComponent(txtGenero)
                            .addComponent(txtTelefono)
                            .addComponent(txtPrograma)
                            .addComponent(txtUniversidad, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(diaRegistroLayout.createSequentialGroup()
                        .addComponent(btnFinRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(btnCancelar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        diaRegistroLayout.setVerticalGroup(
            diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(diaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinRegistro)
                    .addComponent(btnCancelar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        diaDatos.setTitle("DATOS REGISTRADOS");

        cboDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOMBRE", "APELLIDO", "NACIMIENTO", "SEMESTRE", "EMAIL", "GENERO", "TELEFONO", "PROGRAMA", "UNIVERSIDAD" }));
        cboDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDatosActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel18.setText("DATOS INGRESADOS:");

        etiResultado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 2, true));

        etiImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\pngwing.com 150.png")); // NOI18N

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaDatosLayout = new javax.swing.GroupLayout(diaDatos.getContentPane());
        diaDatos.getContentPane().setLayout(diaDatosLayout);
        diaDatosLayout.setHorizontalGroup(
            diaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(diaDatosLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
            .addGroup(diaDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaDatosLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(etiImagen)
                .addGap(136, 136, 136))
        );
        diaDatosLayout.setVerticalGroup(
            diaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaDatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(cboDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(etiImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(diaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(etiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnOk)
                .addGap(25, 25, 25))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTUDIANTES");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("DATOS DEL ESTUDIANTE");

        btnRegistrarse.setText("REGISTRARSE");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(btnRegistrarse)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        diaClave.setSize(460,350);
        diaClave.setLocationRelativeTo(null);
        diaClave.setVisible(true);
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        int may = 0, dig = 0, sim = 0, td, td1 = 0, sum;
        String mensaje = "La clave no cumple con los parametros";
        String mensaje1 = "Las Contraseñas No Son Iguales";
        clave = txtClave.getText();
        clave2 = txtReClave.getText();
        for(int cont = 0; cont < clave.length(); cont ++){
            char caracter = clave.charAt(cont);
            if (Character.isUpperCase(caracter)){
                may = 1;
            }
            if (Character.isLetterOrDigit(caracter)){

            }else{
                sim = 1;
            }
            if (Character.isDigit(caracter)){
                dig = 1;
            }
            td = clave.length();
            if(td >= 8){
                td1 = 1;
            }
        }
        sum = may + sim + dig + td1;
        if (clave.equals(clave2)) {
            if (sum == 4){
                diaClave.dispose();
                diaRegistro.setSize(370,480);
                diaRegistro.setLocationRelativeTo(null);
                diaRegistro.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, mensaje);
            }        
        }else{
            JOptionPane.showMessageDialog(null, mensaje1);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnFinRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinRegistroActionPerformed
        int noid = 0, lido = 0, tre = 0, gen = 0, tele = 0, hrr = 0, unir = 0;
        try{
            id = Integer.parseInt(txtId.getText());
        }catch(java.lang.NumberFormatException error){
            noid = 1;
        }
        int nodi = 0;
        nombre = txtNombre.getText();
        for(int con = 0; con < nombre.length(); con ++){
            char carac = nombre.charAt(con);
            if (Character.isDigit(carac)){
                nodi = 1;
            }
        }
        apellido = txtApellidos.getText();
        for(int co = 0; co < apellido.length(); co ++){
            char lli = apellido.charAt(co);
            if (Character.isDigit(lli)){
                lido = 1;
            }
        }
        fnaci = txtNacimiento.getText();
        try{
            semestre = Integer.parseInt(txtSemestre.getText());
        }catch(java.lang.NumberFormatException error){
            tre = 1;
        }
        email = txtEmail.getText();
        genero = txtGenero.getText();
        if ((genero.equals("Masculino")) || (genero.equals("masculino"))
                || (genero.equals("Femenino")) || (genero.equals("femenino"))) {
            
        }else{
            gen = 1;
        }
        try{
            telefono = Long.parseLong(txtTelefono.getText());
        }catch(java.lang.NumberFormatException error){
            tele = 1;
        }
        programa = txtPrograma.getText();
        for(int ar = 0; ar < programa.length(); ar ++){
            char pro = programa.charAt(ar);
            if(Character.isDigit(pro)){
                    hrr = 1;
            }
        }
        universidad = txtUniversidad.getText();
        for(int dad = 0; dad < universidad.length(); dad ++){
            char versi = universidad.charAt(dad);
            if(Character.isDigit(versi)){
                unir = 1;
            }
        }
        if (noid == 0) {
            if (nodi == 0) {
               if (lido == 0) {
                   if (tre == 0) {
                       if (gen == 0) {
                           if (tele == 0) {
                               if (hrr == 0) {
                                   if (unir == 0) {                                      
                                       diaDatos.setSize(400,350);
                                       diaDatos.setLocationRelativeTo(null);
                                       diaDatos.setVisible(true);
                                       diaRegistro.dispose();
                                   }else{
                                        JOptionPane.showMessageDialog(null, "UNIVERSIDAD no cumple con los parametros");
                                    }
                               }else{
                                    JOptionPane.showMessageDialog(null, "El PROGRAMA no cumple con los parametros");
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "El TELEFONO no cumple con los parametros");
                            }
                       }else{
                            JOptionPane.showMessageDialog(null, "El GENERO no cumple con los parametros");
                        }
                   }else{
                        JOptionPane.showMessageDialog(null, "El SEMESTRE no cumple con los parametros");
                    }
               }else{
                    JOptionPane.showMessageDialog(null, "El APELLIDO no cumple con los parametros");
                }
            }else{
                JOptionPane.showMessageDialog(null, "El NOMBRE no cumple con los parametros");
            }
        }else{
            JOptionPane.showMessageDialog(null, "El ID no cumple con los parametros");
        }
    }//GEN-LAST:event_btnFinRegistroActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        diaRegistro.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDatosActionPerformed
        String mensaje = cboDatos.getSelectedItem().toString();
        if (mensaje.equals("ID")) {
            etiResultado.setText(" " + id );
        }else {
            if (mensaje.equals("NOMBRE")){
                etiResultado.setText(" " + nombre );
            }else{ 
                if (mensaje.equals("APELLIDO")) {
                    etiResultado.setText(" " + apellido );
                } else{                   
                    if (mensaje.equals("NACIMIENTO")){
                        etiResultado.setText(" " + fnaci );
                    }else{
                        if (mensaje.equals("SEMESTRE")){
                            etiResultado.setText(" " + semestre );
                        }else{
                            if (mensaje.equals("EMAIL")) {
                                etiResultado.setText(" " + email );
                            }else{
                                if (mensaje.equals("GENERO")) {
                                    etiResultado.setText(" " + genero );
                                }else{
                                    if (mensaje.equals("TELEFONO")){
                                        etiResultado.setText(" " + telefono );
                                    }else{
                                        if (mensaje.equals("SEMESTRE")){
                                            etiResultado.setText(" " + semestre );
                                        }else{
                                            if (mensaje.equals("PROGRAMA")) {
                                                etiResultado.setText(" " + programa );
                                            }else{
                                                if (mensaje.equals("UNIVERSIDAD")){
                                                    etiResultado.setText(" " + universidad );
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }                   
                }     
            }
        }
    }//GEN-LAST:event_cboDatosActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        diaDatos.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnFinRegistro;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboDatos;
    private javax.swing.JDialog diaClave;
    private javax.swing.JDialog diaDatos;
    private javax.swing.JDialog diaRegistro;
    private javax.swing.JLabel etiClave;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrograma;
    private javax.swing.JTextField txtReClave;
    private javax.swing.JTextField txtSemestre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUniversidad;
    // End of variables declaration//GEN-END:variables
}
